### ISSUE TITLE
Add servers

### ISSUE THREAD

**Issue by mehdifirefox** [daodao97/SingBox#3]
Thank you very much for making it easy to work with this tool for Windows
I use free server
I have to update always

Is there a way we can select active servers and automate disabled servers

I mean not always edit the configgling file
--------------------------
Because I am a beginner
Please edit which lines to add to Trojan or VMESS servers

**Comment by daodao97** [comment]
Maybe it's better that way to write a script to build `config.json`.

**Comment by mehdifirefox** [comment]
> شاید بهتر باشد اینطوری یک اسکریپت برای ساخت بنویسیم `config.json`.

Many people like me change a lot of servers

Editing is a difficult task
Be a script that can make the job easier. It is better
Thankful
