### ISSUE TITLE
Build  with_quic client version

### ISSUE THREAD

**Issue by cbjn** [daodao97/SingBox#5]
Add full hysteria configuration support support.

[](https://sing-box.sagernet.org/configuration/outbound/hysteria)

{
  "type": "hysteria",
  "tag": "hysteria-out",

  "server": "127.0.0.1",
  "server_port": 1080,
  "up": "100 Mbps",
  "up_mbps": 100,
  "down": "100 Mbps",
  "down_mbps": 100,
  "auth": "",
  "auth_str": "password",
  "recv_window_conn": 0,
  "recv_window": 0,
  "disable_mtu_discovery": false,
  "network": "tcp",
  "tls": {},

  ... // Dial Fields
}

**Comment by daodao97** [comment]
[v1.2.0](https://github.com/daodao97/SingBox/releases/tag/v1.2.0)
